CarShop/CarShopIdentityManagementMVC/Controllers/CarInventoryController.cs
using DataObjectsLayer;
using LogicLayer;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarShopIdentityManagementMVC.Controllers
{
    [Authorize]
    public class CarInventoryController : Controller
    {
        private ICarInventoryManager carInventoryManager;
        private IUserManager userManager;
        public CarInventoryController()
        {
            carInventoryManager = new CarInventoryManager();
            userManager = new UserManager();
        }

        // GET: CarInventory
        public ActionResult Index()
        {
            ViewBag.UserEmail = User.Identity.GetUserName().ToString();
            List<CarInventoryVM> cars = carInventoryManager.ViewCarInventory();         
            return View(cars);                       
        }

        // GET: CarInventory/Details/5
        public ActionResult Details(int id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            CarInventoryVM carInventoryVM = carInventoryManager.ViewCarByID(id);
            if(carInventoryVM == null)
            {
                return RedirectToAction("Index");
            }
            return View(carInventoryVM);
        }

        public CarInventoryVM SetUpViewModel()
        {
            CarInventoryVM carInventoryVM = new CarInventoryVM();
            var fuelTypeNames = new List<string> { "Gasoline", "Diesel", "E85", "Ethanl", "Hybrid" };
            var transmissionTypeNames = new List<string> { "Automatic", "Manual" };
            var customerEmails = userManager.GetCustomerEmails();
            carInventoryVM.TransmissionTypeSelectionList = transmissionTypeNames.Select(f => new SelectListItem() { Value = f, Text = f });
            carInventoryVM.FuelTypeSelectionList = fuelTypeNames.Select(f => new SelectListItem() { Value = f, Text = f });
            carInventoryVM.CustomerEmailSelectionList = customerEmails.Select(f => new SelectListItem() { Value = f, Text = f });
            return carInventoryVM;
        }

        public CarInventoryVM AddSelectionListsViewModel(CarInventoryVM carInventoryVM)
        {
            var fuelTypeNames = new List<string> { "Gasoline", "Diesel", "E85", "Ethanl", "Hybrid" };
            var transmissionTypeNames = new List<string> { "Automatic", "Manual" };
            var customerEmails = userManager.GetCustomerEmails();
            carInventoryVM.TransmissionTypeSelectionList = transmissionTypeNames.Select(f => new SelectListItem() { Value = f, Text = f });
            carInventoryVM.FuelTypeSelectionList = fuelTypeNames.Select(f => new SelectListItem() { Value = f, Text = f });
            carInventoryVM.CustomerEmailSelectionList = customerEmails.Select(f => new SelectListItem() { Value = f, Text = f });
            return carInventoryVM;
        }

        // GET: CarInventory/Create
        [Authorize(Roles = "MANAGER, ADMIN, EMPLOYEE")]
        public ActionResult Create()
        {
            CarInventoryVM carInventoryVM = SetUpViewModel();
            return View(carInventoryVM);
        }

        // POST: CarInventory/Create
        [HttpPost]
        [Authorize(Roles = "MANAGER, ADMIN, EMPLOYEE")]
        public ActionResult Create(CarInventoryVM carInventoryVM)
        {
            if (!ModelState.IsValid)
            {
                carInventoryVM = AddSelectionListsViewModel(carInventoryVM);
                return View(carInventoryVM);
            }
            try
            {
                carInventoryManager.InsertNewCar(carInventoryVM.Model, carInventoryVM.Year,
                    carInventoryVM.Color, carInventoryVM.VIN, carInventoryVM.Price,
                    carInventoryVM.Mileage, carInventoryVM.FuelType, carInventoryVM.TransmissionType,
                    carInventoryVM.EngineSize, carInventoryVM.Description);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CarInventory/Edit/5
        [Authorize(Roles = "MANAGER, ADMIN, EMPLOYEE")]
        public ActionResult Edit(Int32 id)
        {
            CarInventoryVM carInventoryVM = carInventoryManager.ViewCarByID(id);
            carInventoryVM = AddSelectionListsViewModel(carInventoryVM);
            return View(carInventoryVM);
        }

        // POST: CarInventory/Edit/5
        [HttpPost]
        [Authorize(Roles = "MANAGER, ADMIN, EMPLOYEE")]
        public ActionResult Edit(CarInventoryVM carInventoryVM)
        {

            if (!ModelState.IsValid)
            {
                carInventoryVM = AddSelectionListsViewModel(carInventoryVM);
                return View(carInventoryVM);
            }
            try
            {
                if (carInventoryVM.CustomerEmail == null)
                {
                    carInventoryVM.CustomerEmail = "";
                }
                carInventoryManager.UpdateCar(carInventoryVM.CarID, carInventoryVM.CustomerEmail, carInventoryVM.Model, carInventoryVM.Year,
                    carInventoryVM.Color, carInventoryVM.VIN, carInventoryVM.Price,
                    carInventoryVM.Mileage, carInventoryVM.FuelType, carInventoryVM.TransmissionType,
                    carInventoryVM.EngineSize, carInventoryVM.Description);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        // GET: CarInventory/Delete/5
        [Authorize(Roles = "MANAGER, ADMIN, EMPLOYEE")]
        public ActionResult Delete(int id)
        {
            CarInventoryVM carInventoryVM = carInventoryManager.ViewCarByID(id);
            return View(carInventoryVM);
        }

        // POST: CarInventory/Delete/5
        [HttpPost]
        [Authorize(Roles = "MANAGER, ADMIN, EMPLOYEE")]
        public ActionResult Delete(int id, CarInventoryVM carInventoryVM)
        {
            try
            {
                carInventoryManager.DeleteCarByID(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CarShop/CarShopIdentityManagementMVC/Controllers/ServiceAppointmentController.cs
using DataObjectsLayer;
using LogicLayer;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace CarShopIdentityManagementMVC.Controllers
{
    [Authorize(Roles = "MANAGER, ADMIN, CUSTOMER")]
    public class ServiceAppointmentController : Controller
    {
        private IServiceAppointmentManager _serviceAppointmentManager;
        private IUserManager _userManager;
        private ICarInventoryManager _carInventoryManager;
        public ServiceAppointmentController()
        {
            _serviceAppointmentManager = new ServiceAppointmentManager();
            _userManager = new UserManager();
            _carInventoryManager = new CarInventoryManager();
        }

        public ServiceAppointmentVM SetUpViewModel()
        {
            ServiceAppointmentVM serviceAppointmentVM = new ServiceAppointmentVM();
            var serviceTypeNames = new List<string> { "Repairs", "Tires", "Oil Change", "Brakes" };
            serviceAppointmentVM.ServiceTypeSelectionList = serviceTypeNames.Select(f => new SelectListItem() { Value = f, Text = f });
            return serviceAppointmentVM;
        }

        public ServiceAppointmentVM AddSelectionListsViewModel(ServiceAppointmentVM serviceAppointmentVM)
        {
            var serviceTypeNames = new List<string> { "Repairs", "Tires", "Oil Change", "Brakes" };
            serviceAppointmentVM.ServiceTypeSelectionList = serviceTypeNames.Select(f => new SelectListItem() { Value = f, Text = f });
            return serviceAppointmentVM;
        }

        // GET: ServiceAppointment
        public ActionResult Index()
        {
            string UserEmail = User.Identity.GetUserName().ToString();
            List<ServiceAppointmentVM> serviceAppointmentVMs = null;
            if (User.IsInRole("CUSTOMER")) 
            {
                serviceAppointmentVMs = _serviceAppointmentManager.RetrieveServiceAppointments();
                foreach (ServiceAppointmentVM serviceAppointmentVM in serviceAppointmentVMs)
                {
                    serviceAppointmentVM.CarModel = _carInventoryManager.ViewCarByID(serviceAppointmentVM.CarID).Model;
                    serviceAppointmentVM.ServiceTypeName = _serviceAppointmentManager.RetrieveServiceTypeByID(serviceAppointmentVM.ServiceTypeID).ServiceDescription;
                }
                ViewBag.UserEmail = User.Identity.GetUserName().ToString();
                return View(serviceAppointmentVMs.Where(item => item.CustomerEmail == UserEmail));
            }
            serviceAppointmentVMs = _serviceAppointmentManager.RetrieveServiceAppointments();
            foreach (ServiceAppointmentVM serviceAppointmentVM in serviceAppointmentVMs)
            {
                serviceAppointmentVM.CarModel = _carInventoryManager.ViewCarByID(serviceAppointmentVM.CarID).Model;
                serviceAppointmentVM.ServiceTypeName = _serviceAppointmentManager.RetrieveServiceTypeByID(serviceAppointmentVM.ServiceTypeID).ServiceDescription;
            }
            return View(serviceAppointmentVMs);
        }

        // GET: ServiceAppointment/Details/5
        public ActionResult Details(int id)
        {
            ServiceAppointmentVM serviceAppointmentVM = _serviceAppointmentManager.RetrieveServiceAppointmentByAppointmentID(id);            
            return View(serviceAppointmentVM);
        }

        // GET: ServiceAppointment/Create
        public ActionResult Create(int id)
        {
            CarInventoryVM carInventoryVM = _carInventoryManager.ViewCarByID(id);
            ServiceAppointmentVM serviceAppointmentVM = new ServiceAppointmentVM();
            serviceAppointmentVM.CustomerEmail = carInventoryVM.CustomerEmail;
            serviceAppointmentVM.CarID = carInventoryVM.CarID;
            serviceAppointmentVM = AddSelectionListsViewModel(serviceAppointmentVM);
            return View(serviceAppointmentVM);
        }

        // POST: ServiceAppointment/Create
        [HttpPost]
        public ActionResult Create(ServiceAppointmentVM serviceAppointmentVM)
        {
            if (!ModelState.IsValid)
            {
                serviceAppointmentVM = AddSelectionListsViewModel(serviceAppointmentVM);
                return View(serviceAppointmentVM);
            }
            try
            {
                // TODO: Add insert logic here
                serviceAppointmentVM.ServiceTypeID = _serviceAppointmentManager.RetrieveServiceTypeByDescription(serviceAppointmentVM.ServiceTypeName).ServiceTypeID;
                _serviceAppointmentManager.CreateNewServiceAppointment(serviceAppointmentVM.CarID, serviceAppointmentVM.CustomerEmail, serviceAppointmentVM.ServiceTypeID, serviceAppointmentVM.CustomerComments, serviceAppointmentVM.ScheduledDate);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ServiceAppointment/Edit/5
        public ActionResult Edit(int id)
        {
            ServiceAppointmentVM serviceAppointmentVM = _serviceAppointmentManager.RetrieveServiceAppointmentByAppointmentID(id);
            serviceAppointmentVM = AddSelectionListsViewModel(serviceAppointmentVM);
            return View(serviceAppointmentVM);
        }

        // POST: ServiceAppointment/Edit/5
        [HttpPost]
        public ActionResult Edit(ServiceAppointmentVM serviceAppointmentVM)
        {
            if (!ModelState.IsValid)
            {                
                serviceAppointmentVM = AddSelectionListsViewModel(serviceAppointmentVM);
                return View(serviceAppointmentVM);
            }
            try
            {
                serviceAppointmentVM.ServiceTypeID = _serviceAppointmentManager.RetrieveServiceTypeByDescription(serviceAppointmentVM.ServiceTypeName).ServiceTypeID;
                _serviceAppointmentManager.UpdateServiceAppointment(serviceAppointmentVM.AppointmentID, serviceAppointmentVM.CarID,
                    serviceAppointmentVM.CustomerEmail, serviceAppointmentVM.ServiceTypeID, serviceAppointmentVM.CustomerComments,
                    serviceAppointmentVM.ScheduledDate);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ServiceAppointment/Delete/5
        public ActionResult Delete(int id)
        {
            ServiceAppointmentVM serviceAppointmentVM = _serviceAppointmentManager.RetrieveServiceAppointmentByAppointmentID(id);
            return View(serviceAppointmentVM);
        }

        // POST: ServiceAppointment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ServiceAppointmentVM serviceAppointmentVM)
        {
            try
            {
                _serviceAppointmentManager.DeleteServiceAppointmentByAppointmentID(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CarShop/CarShopIdentityManagementMVC/Views/CarInventory/Create.cshtml
@model DataObjectsLayer.CarInventoryVM

@{
    ViewBag.Title = "Add a new car.";
}

<h2>Add New Car</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VIN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VIN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VIN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Mileage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mileage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mileage, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-2">
                @Html.LabelFor(model => model.FuelType, htmlAttributes: new { @class = "control-label col-md-2 fw-bold" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.FuelType, Model.FuelTypeSelectionList,
                                                                "Fuel Type", new { @class = "py-1 px-1 w-100" })
                    @Html.ValidationMessageFor(model => model.FuelType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-2">
                @Html.LabelFor(model => model.TransmissionType, htmlAttributes: new { @class = "control-label col-md-2 fw-bold" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.TransmissionType, Model.TransmissionTypeSelectionList,
                                        "Transmission Type", new { @class = "py-1 px-1 w-100" })
                    @Html.ValidationMessageFor(model => model.TransmissionType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EngineSize, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EngineSize, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EngineSize, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>        
                
        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <br/>
    @Html.ActionLink("Back to List", "Index")
</div>

CarShop/CarShopIdentityManagementMVC/Views/CarInventory/Delete.cshtml
@model DataObjectsLayer.CarInventoryVM

@{
    ViewBag.Title = "Delete a car";
}

<h2>Delete</h2>

    <div class="col-md-6 offset-md-3">
        <h3 class="text-danger">Are you sure you want to delete this?</h3>
        <hr />
            <table class="table">
                <tr>
                    <td class="px-2 fw-bold">
                        @Html.DisplayNameFor(model => model.CarID):
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CarID)
                    </td>
                </tr>
                <tr>
                    <td class="px-2 fw-bold">
                        @Html.DisplayNameFor(model => model.Model):
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Model)
                    </td>
                </tr>
                <tr>
                    <td class="px-2 fw-bold">
                        @Html.DisplayNameFor(model => model.Year):
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Year)
                    </td>
                </tr>
                <tr>
                    <td class="px-2 fw-bold">
                        @Html.DisplayNameFor(model => model.Color):
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Color)
                    </td>
                </tr>
                <tr>
                    <td class="px-2 fw-bold">
                        @Html.DisplayNameFor(model => model.Price):
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Price)
                    </td>
                </tr>
                <tr>
                    <td class="px-2 fw-bold">
                        @Html.DisplayNameFor(model => model.EngineSize):
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.EngineSize)
                    </td>
                </tr>
            </table>

            

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color text-center">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <br />
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

CarShop/CarShopIdentityManagementMVC/Views/CarInventory/Details.cshtml
@model DataObjectsLayer.CarInventoryVM

@{
    ViewBag.Title = "Car Details";
}

<h2>Car Details</h2>

<div>
    <hr />   
                <table class="table">
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.CarID):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.CarID)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.CustomerEmail):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.CustomerEmail)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.Model):
                        </td>
                        <td class="text-capitalize">
                            @Html.DisplayFor(model => model.Model)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.Year):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Year)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.Color):
                        </td>
                        <td class="text-capitalize">
                            @Html.DisplayFor(model => model.Color)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.VIN):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.VIN)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.Price):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Price)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.Mileage):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Mileage)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.FuelType):
                        </td>
                        <td class="text-capitalize">
                            @Html.DisplayFor(model => model.FuelType)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.TransmissionType):
                        </td>
                        <td class="text-capitalize">
                            @Html.DisplayFor(model => model.TransmissionType)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.EngineSize):
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.EngineSize)
                        </td>
                    </tr>
                    <tr>
                        <td class="px-2 fw-bold">
                            @Html.DisplayNameFor(model => model.Description):
                        </td>
                        <td class="text-capitalize">
                            @Html.DisplayFor(model => model.Description)
                        </td>
                    </tr>
                </table>                     
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CarID }, new { @class = "btn btn-secondary" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarShop/CarShopIdentityManagementMVC/Views/CarInventory/Index.cshtml
@model IEnumerable<DataObjectsLayer.CarInventoryVM>

@{
    ViewBag.Title = "Car Inventory";
}

<h2 class="animate__animated animate__flipInY">Car Inventory</h2>

    <p>
        @if (User.IsInRole("MANAGER") || User.IsInRole("ADMIN") || User.IsInRole("EMPLOYEE"))
        {
            @Html.ActionLink("Add new car", "Create", "CarInventory", null, new { @class = "btn btn-success" })
        }
    </p>
    <table class="table table-bordered table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CarID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mileage)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CarID)
                </td>
                <td style="text-transform: capitalize">
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td style="text-transform: capitalize">
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Mileage)
                </td>
                <td>
                    @if (User.IsInRole("MANAGER") || User.IsInRole("ADMIN") || User.IsInRole("EMPLOYEE"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.CarID }, new { @class = "btn btn-secondary", style = "Width: 5rem; margin-right: 5px;" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.CarID }, new { @class = "btn btn-danger", style = "Width: 5rem;" })
                    }
                    @Html.ActionLink("Details", "Details", new { id = item.CarID }, new { @class = "btn btn-info", style = "Width: 5rem;" })
                    @if (User.IsInRole("CUSTOMER") && (string)ViewBag.UserEmail == item.CustomerEmail)
                    {
                        @Html.ActionLink("Service", "Create", "ServiceAppointment", new { id = item.CarID }, new { @class = "btn btn-warning", style = "Width: 5rem;" })
                    }
                </td>
            </tr>
        }

    </table>